// Code generated by protoc-gen-go-grpc. DO NOT EDIT.

package gameengine

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// GameEngineClient is the client API for GameEngine service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type GameEngineClient interface {
	GetSize(ctx context.Context, in *GetSizeRequest, opts ...grpc.CallOption) (*GetSizeResponse, error)
	SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error)
}

type gameEngineClient struct {
	cc grpc.ClientConnInterface
}

func NewGameEngineClient(cc grpc.ClientConnInterface) GameEngineClient {
	return &gameEngineClient{cc}
}

func (c *gameEngineClient) GetSize(ctx context.Context, in *GetSizeRequest, opts ...grpc.CallOption) (*GetSizeResponse, error) {
	out := new(GetSizeResponse)
	err := c.cc.Invoke(ctx, "/ms.gameengine.v1.GameEngine/GetSize", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *gameEngineClient) SetScore(ctx context.Context, in *SetScoreRequest, opts ...grpc.CallOption) (*SetScoreResponse, error) {
	out := new(SetScoreResponse)
	err := c.cc.Invoke(ctx, "/ms.gameengine.v1.GameEngine/SetScore", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// GameEngineServer is the server API for GameEngine service.
// All implementations must embed UnimplementedGameEngineServer
// for forward compatibility
type GameEngineServer interface {
	GetSize(context.Context, *GetSizeRequest) (*GetSizeResponse, error)
	SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error)
	mustEmbedUnimplementedGameEngineServer()
}

// UnimplementedGameEngineServer must be embedded to have forward compatible implementations.
type UnimplementedGameEngineServer struct {
}

func (UnimplementedGameEngineServer) GetSize(context.Context, *GetSizeRequest) (*GetSizeResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetSize not implemented")
}
func (UnimplementedGameEngineServer) SetScore(context.Context, *SetScoreRequest) (*SetScoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SetScore not implemented")
}
func (UnimplementedGameEngineServer) mustEmbedUnimplementedGameEngineServer() {}

// UnsafeGameEngineServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to GameEngineServer will
// result in compilation errors.
type UnsafeGameEngineServer interface {
	mustEmbedUnimplementedGameEngineServer()
}

func RegisterGameEngineServer(s grpc.ServiceRegistrar, srv GameEngineServer) {
	s.RegisterService(&GameEngine_ServiceDesc, srv)
}

func _GameEngine_GetSize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSizeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).GetSize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.gameengine.v1.GameEngine/GetSize",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).GetSize(ctx, req.(*GetSizeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _GameEngine_SetScore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetScoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(GameEngineServer).SetScore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/ms.gameengine.v1.GameEngine/SetScore",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(GameEngineServer).SetScore(ctx, req.(*SetScoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// GameEngine_ServiceDesc is the grpc.ServiceDesc for GameEngine service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var GameEngine_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ms.gameengine.v1.GameEngine",
	HandlerType: (*GameEngineServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetSize",
			Handler:    _GameEngine_GetSize_Handler,
		},
		{
			MethodName: "SetScore",
			Handler:    _GameEngine_SetScore_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "game-engine.proto",
}
